# Generated by Django 4.2.7 on 2023-11-20 02:47

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DomainEPSG",
            fields=[
                (
                    "dom_cd_epsg",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name="EPSG Code"
                    ),
                ),
                (
                    "dom_sg_epsg",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="EPSG Acronym"
                    ),
                ),
                (
                    "dom_nm_epsg",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="EPSG Name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DomainFormat",
            fields=[
                (
                    "dom_sg_format",
                    models.CharField(
                        max_length=4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Format Acronym",
                    ),
                ),
                (
                    "dom_nm_format",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Format Name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DomainType",
            fields=[
                (
                    "dom_cd_type",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Type code"
                    ),
                ),
                (
                    "dom_sg_type",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Type Acronym"
                    ),
                ),
                (
                    "dom_nm_type",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Type Name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinalDatabase",
            fields=[
                (
                    "fdb_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Primary Key"
                    ),
                ),
                (
                    "fdb_database_name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Final Database Name"
                    ),
                ),
                (
                    "fdb_storageplace",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Storage Place",
                    ),
                ),
                (
                    "fdb_database_active",
                    models.BooleanField(
                        default=False, verbose_name="Database is Active"
                    ),
                ),
                (
                    "fdb_webportal_active",
                    models.BooleanField(
                        default=False, verbose_name="Webportal is Active"
                    ),
                ),
                (
                    "fdb_moved",
                    models.BooleanField(
                        default=False, verbose_name="Files were totally moved"
                    ),
                ),
                (
                    "fdb_format",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_satoc.domainformat",
                        verbose_name="Format",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OriginalFolderSource",
            fields=[
                (
                    "ofs_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Primary Key"
                    ),
                ),
                (
                    "ofs_name",
                    models.CharField(max_length=80, unique=True, verbose_name="Name"),
                ),
                (
                    "ofs_receiptdate",
                    models.DateField(
                        blank=True, null=True, verbose_name="Receipt Date"
                    ),
                ),
                (
                    "ofs_meansofreceipt",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Means of Receipt",
                    ),
                ),
                (
                    "ofs_storageplace",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Storage Place",
                    ),
                ),
                (
                    "ofs_size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Size (MB)"
                    ),
                ),
                (
                    "ofs_featureclass",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Number of feature classes"
                    ),
                ),
                (
                    "ofs_email",
                    models.BooleanField(default=False, verbose_name="Email attached"),
                ),
                (
                    "ofs_description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "ofs_format",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_satoc.domainformat",
                        verbose_name="Format",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OriginalFileName",
            fields=[
                (
                    "ofn_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Primary Key"
                    ),
                ),
                (
                    "ofn_featureclass",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        unique=True,
                        verbose_name="Original Feature Class Name",
                    ),
                ),
                (
                    "ofn_featuredataset",
                    models.CharField(
                        max_length=80, verbose_name="Original Feature Dataset Name"
                    ),
                ),
                (
                    "ofn_attributes",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Number of attributes"
                    ),
                ),
                (
                    "ofn_attached_photos",
                    models.BooleanField(default=False, verbose_name="Attached photos"),
                ),
                (
                    "ofn_description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "ofn_epsg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_satoc.domainepsg",
                        verbose_name="EPSG",
                    ),
                ),
                (
                    "ofn_format",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_satoc.domainformat",
                        verbose_name="Format",
                    ),
                ),
                (
                    "ofn_ofs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app_satoc.originalfoldersource",
                        verbose_name="Original Folder Name",
                    ),
                ),
                (
                    "ofn_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_satoc.domaintype",
                        verbose_name="Type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinalFileName",
            fields=[
                (
                    "ffn_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Primary Key"
                    ),
                ),
                (
                    "ffn_featureclass",
                    models.CharField(
                        max_length=80,
                        unique=True,
                        verbose_name="Final Feature Class Name",
                    ),
                ),
                (
                    "ffn_featuredataset",
                    models.CharField(
                        max_length=80, verbose_name="Final Feature Dataset Name"
                    ),
                ),
                (
                    "ffn_standard_sdsfie",
                    models.BooleanField(
                        default=False, verbose_name="Adheres to the SDSFIE standard"
                    ),
                ),
                (
                    "ffn_description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "ffn_epsg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_satoc.domainepsg",
                        verbose_name="EPSG",
                    ),
                ),
                (
                    "ffn_fdb",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_satoc.finaldatabase",
                        verbose_name="Final Database",
                    ),
                ),
                (
                    "ffn_format",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_satoc.domainformat",
                        verbose_name="Format",
                    ),
                ),
                (
                    "ffn_ofn",
                    smart_selects.db_fields.ChainedForeignKey(
                        auto_choose=True,
                        chained_field="ffn_ofs",
                        chained_model_field="ofn_ofs",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_satoc.originalfilename",
                        verbose_name="Original File Name",
                    ),
                ),
                (
                    "ffn_ofs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_satoc.originalfoldersource",
                        verbose_name="Original Folder Source",
                    ),
                ),
                (
                    "ffn_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_satoc.domaintype",
                        verbose_name="Type",
                    ),
                ),
            ],
        ),
    ]
