# Generated by Django 4.2.7 on 2023-11-20 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_satoc", "0002_alter_domainepsg_dom_nm_epsg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="originalfilename",
            name="ofn_ofs",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app_satoc.originalfoldersource",
                verbose_name="Original Folder Name",
            ),
        ),
    ]
